# Generated by Django 3.2.7 on 2023-05-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('made_in', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('estimated_time', models.CharField(max_length=255)),
                ('custom_size', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
