# Generated by Django 3.2.7 on 2023-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.CharField(max_length=255),
        ),
    ]
