# Generated by Django 3.2.7 on 2023-05-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
