# Generated by Django 3.2.7 on 2023-06-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230611_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_category', models.CharField(max_length=255)),
                ('finish', models.CharField(max_length=255)),
                ('available_in', models.CharField(max_length=255)),
                ('material_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_model', to='base.product')),
            ],
        ),
    ]
